# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Ckeck Frontend

on:
  push:
    paths:
      - 'frontend/**'

jobs:
  verify:
    name: Setup, Check and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install
        
      - name: Run Lint
        working-directory: ./frontend
        run: npm run lint

      - name: Build
        working-directory: ./frontend
        run: npm run build
